


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_cron" WITH SCHEMA "pg_catalog";






CREATE EXTENSION IF NOT EXISTS "pgsodium";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";






CREATE TYPE "public"."event_type" AS ENUM (
    'get_song'
);


ALTER TYPE "public"."event_type" OWNER TO "postgres";


CREATE TYPE "public"."strophe_quality" AS ENUM (
    'VERSE',
    'BRIDGE',
    'CHORUS'
);


ALTER TYPE "public"."strophe_quality" OWNER TO "postgres";


CREATE OR REPLACE FUNCTION "public"."get_popular_songs"("start_date" "text" DEFAULT NULL::"text", "end_date" "text" DEFAULT NULL::"text") RETURNS TABLE("title" "text", "count" bigint)
    LANGUAGE "sql"
    AS $$
      SELECT
          s.title,
          COUNT(analytics.id) as count
      FROM analytics 
      INNER JOIN songs s ON analytics."songId" = s.id
      WHERE
          (start_date IS NULL OR analytics.created_at >= start_date::date)
          AND (end_date IS NULL OR analytics.created_at <= end_date::date)
      GROUP BY s.id, s.title
      ORDER BY count DESC;
  $$;


ALTER FUNCTION "public"."get_popular_songs"("start_date" "text", "end_date" "text") OWNER TO "postgres";

SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."analytics" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "songId" bigint
);


ALTER TABLE "public"."analytics" OWNER TO "postgres";


ALTER TABLE "public"."analytics" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."analytics_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."leader_position" (
    "leader_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "song" bigint,
    "setlist_item" bigint
);


ALTER TABLE "public"."leader_position" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."mass_suggestions" (
    "date" "date" NOT NULL,
    "suggestions" "jsonb" NOT NULL,
    "liturgical_summary" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."mass_suggestions" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."ordinaires" (
    "id" integer NOT NULL,
    "name" "text" NOT NULL,
    "sheet_music_url" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."ordinaires" OWNER TO "postgres";


CREATE SEQUENCE IF NOT EXISTS "public"."ordinaires_id_seq"
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


ALTER SEQUENCE "public"."ordinaires_id_seq" OWNER TO "postgres";


ALTER SEQUENCE "public"."ordinaires_id_seq" OWNED BY "public"."ordinaires"."id";



CREATE TABLE IF NOT EXISTS "public"."setlist_items" (
    "song_id" bigint,
    "setlist_id" bigint NOT NULL,
    "position" bigint NOT NULL,
    "id" bigint NOT NULL,
    "text" "text",
    "text_id" bigint
);


ALTER TABLE "public"."setlist_items" OWNER TO "postgres";


ALTER TABLE "public"."setlist_items" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."setlist_items_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."setlist_items" ALTER COLUMN "position" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."setlist_items_position_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."setlists" (
    "id" bigint NOT NULL,
    "name" "text",
    "created_at" timestamp with time zone DEFAULT "now"()
);


ALTER TABLE "public"."setlists" OWNER TO "postgres";


ALTER TABLE "public"."setlists" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."setlists_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."slideshow_position" (
    "slideshow_id" "text" NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "updated_at" timestamp without time zone DEFAULT "now"() NOT NULL,
    "song" bigint,
    "step" bigint
);


ALTER TABLE "public"."slideshow_position" OWNER TO "postgres";


COMMENT ON TABLE "public"."slideshow_position" IS 'Position of a desktop in slideshow mode';



CREATE TABLE IF NOT EXISTS "public"."song_requests" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" "text" NOT NULL,
    "is_done" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."song_requests" OWNER TO "postgres";


ALTER TABLE "public"."song_requests" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."song_requests_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."song_tag" (
    "song_id" bigint NOT NULL,
    "tag_id" bigint NOT NULL
);


ALTER TABLE "public"."song_tag" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."songs" (
    "id" bigint NOT NULL,
    "title" "text" NOT NULL,
    "strophes" "jsonb"[],
    "sheet_music_url" "text",
    "type" "text" DEFAULT 'song'::"text" NOT NULL,
    "ordinaire_id" integer,
    "ordinaire_role" "text"
);


ALTER TABLE "public"."songs" OWNER TO "postgres";


ALTER TABLE "public"."songs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."songs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."tags" (
    "id" bigint NOT NULL,
    "name" "text",
    "color" "text",
    "svg" "text"
);


ALTER TABLE "public"."tags" OWNER TO "postgres";


ALTER TABLE "public"."tags" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tags_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."texts" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "content" "text" NOT NULL,
    "title" "text" NOT NULL
);


ALTER TABLE "public"."texts" OWNER TO "postgres";


ALTER TABLE "public"."texts" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."texts_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."ordinaires" ALTER COLUMN "id" SET DEFAULT "nextval"('"public"."ordinaires_id_seq"'::"regclass");



ALTER TABLE ONLY "public"."analytics"
    ADD CONSTRAINT "analytics_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."leader_position"
    ADD CONSTRAINT "leader_position_pkey" PRIMARY KEY ("leader_id");



ALTER TABLE ONLY "public"."mass_suggestions"
    ADD CONSTRAINT "mass_suggestions_pkey" PRIMARY KEY ("date");



ALTER TABLE ONLY "public"."ordinaires"
    ADD CONSTRAINT "ordinaires_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."setlist_items"
    ADD CONSTRAINT "setlist_items_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."setlist_items"
    ADD CONSTRAINT "setlist_items_pkey" PRIMARY KEY ("position", "id");



ALTER TABLE ONLY "public"."setlists"
    ADD CONSTRAINT "setlists_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."slideshow_position"
    ADD CONSTRAINT "slideshow_position_pkey" PRIMARY KEY ("slideshow_id");



ALTER TABLE ONLY "public"."song_requests"
    ADD CONSTRAINT "song_requests_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."song_tag"
    ADD CONSTRAINT "song_tag_pkey" PRIMARY KEY ("song_id", "tag_id");



ALTER TABLE ONLY "public"."songs"
    ADD CONSTRAINT "songs_id_key" UNIQUE ("id");



ALTER TABLE ONLY "public"."songs"
    ADD CONSTRAINT "songs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."tags"
    ADD CONSTRAINT "tags_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."texts"
    ADD CONSTRAINT "texts_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."analytics"
    ADD CONSTRAINT "analytics_value_fkey" FOREIGN KEY ("songId") REFERENCES "public"."songs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."leader_position"
    ADD CONSTRAINT "leader_position_setlist_item_fkey" FOREIGN KEY ("setlist_item") REFERENCES "public"."setlist_items"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."leader_position"
    ADD CONSTRAINT "leader_position_song_fkey" FOREIGN KEY ("song") REFERENCES "public"."songs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."setlist_items"
    ADD CONSTRAINT "setlist_items_setlist_id_fkey" FOREIGN KEY ("setlist_id") REFERENCES "public"."setlists"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."setlist_items"
    ADD CONSTRAINT "setlist_items_song_id_fkey" FOREIGN KEY ("song_id") REFERENCES "public"."songs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."setlist_items"
    ADD CONSTRAINT "setlist_items_text_id_fkey" FOREIGN KEY ("text_id") REFERENCES "public"."texts"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."slideshow_position"
    ADD CONSTRAINT "slideshow_position_song_fkey" FOREIGN KEY ("song") REFERENCES "public"."songs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_tag"
    ADD CONSTRAINT "song_tag_song_id_fkey" FOREIGN KEY ("song_id") REFERENCES "public"."songs"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."song_tag"
    ADD CONSTRAINT "song_tag_tag_id_fkey" FOREIGN KEY ("tag_id") REFERENCES "public"."tags"("id") ON UPDATE CASCADE ON DELETE CASCADE;



ALTER TABLE ONLY "public"."songs"
    ADD CONSTRAINT "songs_ordinaire_id_fkey" FOREIGN KEY ("ordinaire_id") REFERENCES "public"."ordinaires"("id") ON DELETE SET NULL;



CREATE POLICY "Anon can insert but not read" ON "public"."analytics" FOR INSERT WITH CHECK (true);



CREATE POLICY "Anon can insert but not read" ON "public"."song_requests" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable insert for all users only" ON "public"."texts" FOR INSERT WITH CHECK (true);



CREATE POLICY "Enable read access for all users" ON "public"."analytics" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."songs" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."tags" FOR SELECT USING (true);



CREATE POLICY "Enable read access for all users" ON "public"."texts" FOR SELECT USING (true);



CREATE POLICY "Enable write access for all users" ON "public"."songs" FOR UPDATE USING (true);



CREATE POLICY "all can create" ON "public"."songs" FOR INSERT WITH CHECK (true);



CREATE POLICY "all can delete" ON "public"."leader_position" FOR DELETE USING (true);



CREATE POLICY "all can do all" ON "public"."slideshow_position" USING (true);



CREATE POLICY "all can insert" ON "public"."leader_position" FOR INSERT WITH CHECK (true);



CREATE POLICY "all can update" ON "public"."leader_position" FOR UPDATE USING (true);



CREATE POLICY "all user can do all" ON "public"."setlists" USING (true);



CREATE POLICY "all user can write" ON "public"."setlist_items" TO "anon" USING (true);



ALTER TABLE "public"."analytics" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."leader_position" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."mass_suggestions" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "mass_suggestions are insertable by anon" ON "public"."mass_suggestions" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "mass_suggestions are readable by anon" ON "public"."mass_suggestions" FOR SELECT TO "anon" USING (true);



CREATE POLICY "mass_suggestions are updatable by anon" ON "public"."mass_suggestions" FOR UPDATE TO "anon" USING (true);



ALTER TABLE "public"."ordinaires" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "ordinaires are deletable by anon" ON "public"."ordinaires" FOR DELETE TO "anon" USING (true);



CREATE POLICY "ordinaires are insertable by anon" ON "public"."ordinaires" FOR INSERT TO "anon" WITH CHECK (true);



CREATE POLICY "ordinaires are readable by anon" ON "public"."ordinaires" FOR SELECT TO "anon" USING (true);



CREATE POLICY "ordinaires are updatable by anon" ON "public"."ordinaires" FOR UPDATE TO "anon" USING (true);



CREATE POLICY "read recent entries" ON "public"."leader_position" FOR SELECT USING (("updated_at" > (CURRENT_TIMESTAMP - '01:00:00'::interval)));



ALTER TABLE "public"."setlist_items" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."setlists" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."slideshow_position" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."song_requests" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."song_tag" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."songs" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."tags" ENABLE ROW LEVEL SECURITY;


ALTER TABLE "public"."texts" ENABLE ROW LEVEL SECURITY;


CREATE POLICY "write access to all users" ON "public"."song_tag" USING (true);





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";






ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."leader_position";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."slideshow_position";



ALTER PUBLICATION "supabase_realtime" ADD TABLE ONLY "public"."songs";






GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";




















































































































































































GRANT ALL ON FUNCTION "public"."get_popular_songs"("start_date" "text", "end_date" "text") TO "anon";
GRANT ALL ON FUNCTION "public"."get_popular_songs"("start_date" "text", "end_date" "text") TO "authenticated";
GRANT ALL ON FUNCTION "public"."get_popular_songs"("start_date" "text", "end_date" "text") TO "service_role";






























GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."analytics" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."analytics" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."analytics" TO "service_role";



GRANT ALL ON SEQUENCE "public"."analytics_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."analytics_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."analytics_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."leader_position" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."leader_position" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."leader_position" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."mass_suggestions" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."mass_suggestions" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."mass_suggestions" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ordinaires" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ordinaires" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."ordinaires" TO "service_role";



GRANT ALL ON SEQUENCE "public"."ordinaires_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."ordinaires_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."ordinaires_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."setlist_items" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."setlist_items" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."setlist_items" TO "service_role";



GRANT ALL ON SEQUENCE "public"."setlist_items_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."setlist_items_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."setlist_items_id_seq" TO "service_role";



GRANT ALL ON SEQUENCE "public"."setlist_items_position_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."setlist_items_position_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."setlist_items_position_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."setlists" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."setlists" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."setlists" TO "service_role";



GRANT ALL ON SEQUENCE "public"."setlists_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."setlists_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."setlists_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."slideshow_position" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."slideshow_position" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."slideshow_position" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."song_requests" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."song_requests" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."song_requests" TO "service_role";



GRANT ALL ON SEQUENCE "public"."song_requests_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."song_requests_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."song_requests_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."song_tag" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."song_tag" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."song_tag" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."songs" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."songs" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."songs" TO "service_role";



GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."songs_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."tags" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."tags" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."tags" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tags_id_seq" TO "service_role";



GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."texts" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."texts" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."texts" TO "service_role";



GRANT ALL ON SEQUENCE "public"."texts_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."texts_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."texts_id_seq" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLES TO "service_role";































